#pragma once
#include <iostream>
#include <io.h>
#include <fcntl.h>
#include <vector>
#include <codecvt>
#include <clocale>
#include <fstream>
#include <ctime>
#include <sstream>
#include <string>
#include <windows.h>
#include <exception>
#include <assert.h>
#include <functional>
#include <array>
#include <typeinfo>
#include <direct.h>
#include <cerrno>
#include <conio.h>
